### ISSUE TITLE
mattress/buy - improve instagram section interaction

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#17]

**Comment by ohnno** [comment]
Let's work through this together.

**Comment by joeldrobertson2** [comment]
I've attempted to fetch videos for this page dynamically from the Greywing Instagram account. Unfortunately it isn't possible to display just the videos due to a technical limitation of the Instagram API. 

It would be very simple for your in house developer to manually update the page template to add a new video. I can provide instructions on how to go about this.

As for improving the interaction did you have anything in mind? We could pop the instagram posts up in a modal window.

**Comment by ohnno** [comment]
No worries that's fine.

It would be great if they could open up in a similar way to the home page video!

**Comment by joeldrobertson2** [comment]
Great! I can easily add the same interaction as the home page video has.

**Comment by ohnno** [comment]
Great thanks Joel, can we add like a 10% dim to the hover of the images too? Thanks!

**Comment by joeldrobertson2** [comment]
A 10% dim has been added to the images on hover.
