### ISSUE TITLE
cart/checkout - implement new cart design as per email spec

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#18]

**Comment by ohnno** [comment]
Let's work through this together.

**Comment by ohnno** [comment]
![step-1](https://cloud.githubusercontent.com/assets/2937538/16071251/bb673a38-331d-11e6-99fa-79b16032c49a.png)
![step-2](https://cloud.githubusercontent.com/assets/2937538/16071252/bb9336ec-331d-11e6-8af9-ffb09286d5cf.png)
![step-3](https://cloud.githubusercontent.com/assets/2937538/16071254/bbbb5a82-331d-11e6-9ca5-a0a586893039.png)

**Comment by tbrown123** [comment]
Honestly I think we should leave the cart alone as discussed in the meeting. Only having the discount on the last page isn't ideal as it's one of the last things you do. If people have to wait that long to get there it may be frustrating. We've had people ask where it since launch and it's currently in two spots.

**Comment by ohnno** [comment]
Hey mate, most of the cart is basically the same, we're just cleaning up some UI since the current cart was temporary for the initial soft-launch.

If voucher codes are an issue now then I can adjust the design to make it much more obvious.

@joeldrobertson2 I'll update this now and repload the mockups.

**Comment by joeldrobertson2** [comment]
I've been able to implement most the checkout checkout design today. Unfortunately there were a few small details that were not possible to achieve.

The order number could not be moved under the paragraph of text.
![image](https://cloud.githubusercontent.com/assets/19680256/16371186/3d2346a2-3c88-11e6-8577-5c47f87e5e09.png)

The order summary totals column and discount field could not be placed in adjacent columns. This is because the totals title is a lot longer than in the artwork and it can't be changed unless you change prices to be non inclusive of tax which is not a great idea!
![image](https://cloud.githubusercontent.com/assets/19680256/16371199/4d2f48b6-3c88-11e6-97be-7687cc288c30.png)
