### ISSUE TITLE
bed base image - homepage

### ISSUE THREAD

**Issue by tbrown123** [ohnno/Greywing#65]
Please go back to the old wooden bed base image if we still have it.

**Comment by ohnno** [comment]
The old bed base image was super low res and just a placeholder - also, it was cropped so that you can only see 1/4 of it. Which makes it very hard for me to edit the image properly, but the main issue is that I can't also have a matching footer image for the base. Lastly it was from google and we don't have copyrights for it.

If you can find a stock image of a wooden base that's of decent resolution and also has the full mattress so that I can use it both the product card and footer card then send it over and we can use it - but I couldn't really find anything.

**Comment by tbrown123** [comment]
that's alright then let's leave it as is.
ᐧ

Cheers,

*Tom Brown*

<http://www.greywing.com.au>

*p: *03 9017 0876
*m:* 0416 804 674
46 Budd Street, Collingwood VIC
www.greywing.com.au
